[toolchain]
channel = "nightly"
components = ["rustfmt", "cargo", "rustfmt", "rust-std", "rust-analyzer", "clippy", "rustc", "llvm-tools-preview"]
targets = ["wasm32-unknown-unknown", "x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "x86_64-apple-darwin"]
profile = "complete"
