name: dashboard-rs
summary: Rust Home Dashboard Frontend
description:
  The kiosk dashboard frontend for the Home Dashboard
base: core22
confinement: strict
parts:
  dashboard-rs:
    plugin: rust
    source: .
    stage-snaps:
      - ubuntu-frame
    build-packages:
      - libgtk-3-dev
      - libwebkit2gtk-4.1-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - libsoup-3.0-dev
      - libjavascriptcoregtk-4.1-dev
    stage-packages:
      - libgtk-3
      - libwebkit2gtk-4.1
      - libayatana-appindicator3
      - librsvg2
      - libsoup-3.0
      - libjavascriptcoregtk-4.1

apps:
  dashboard-rs:
    plugs: [ desktop, desktop-legacy, gsettings, opengl, wayland, x11, mount-observe, calendar-service]
    extensions:
      - gnome
    command: 'bin/dashboard_app_rs'
type: app
version: git