name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup ubuntu
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev libsoup-3.0-dev

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Install NPM Dependencies
        run: npm i

      # Setup Rust
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Install Rust trunk
        uses: taiki-e/install-action@v2
        with:
          tool: trunk
      - name: Install Rust tauri-cli
        uses: taiki-e/install-action@v2
        with:
          tool: tauri-cli

      # Build
      - name: Cargo Build
        run: cargo build --release

      - name: Tauri Build
        run: cargo tauri build --ci

      # Test
      - name: Run component tests
        run: cargo test --package components --verbose

      # TODO Release
